//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipping_details1.edusys {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AttributeCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringanyType")]
    [System.SerializableAttribute()]
    public class AttributeCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, object>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FormattedValueCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfstringstring")]
    [System.SerializableAttribute()]
    public class FormattedValueCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, string>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="RelatedEntityCollection", Namespace="http://schemas.microsoft.com/xrm/2011/Contracts", ItemName="KeyValuePairOfRelationshipEntityCollectionX_PsK4FkN")]
    [System.SerializableAttribute()]
    public class RelatedEntityCollection : System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<Microsoft.Xrm.Sdk.Relationship, Microsoft.Xrm.Sdk.EntityCollection>> {
    }
}
